name: scannut
description: AI Visual Assistant for Nutrition, Botany and Pet Care.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # --- Gerenciamento de Estado ---
  flutter_riverpod: ^2.5.1

  # --- Interface e Design ---
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  font_awesome_flutter: ^10.7.0
  percent_indicator: ^4.2.3
  flutter_staggered_animations: ^1.1.1

  # --- CÃ¢mera e Imagem ---
  camera: ^0.11.0+2
  path_provider: ^2.1.3
  path: ^1.9.0

  # --- API e Rede ---
  dio: ^5.4.3+1
  flutter_dotenv: ^5.1.0

  # --- Utilidades ---
  url_launcher: ^6.2.6
  intl: ^0.20.2
  permission_handler: ^11.1.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  # --- Ativos do App ---
  assets:
    - .env
    - assets/animations/
    - assets/images/
