name: scannut
description: AI Visual Assistant for Nutrition, Botany and Pet Care.
publish_to: "none"
version: 7.2.1+24

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # --- Gerenciamento de Estado ---
  flutter_riverpod: ^2.5.1

  # --- Interface e Design ---
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  font_awesome_flutter: ^10.7.0
  percent_indicator: ^4.2.3
  flutter_staggered_animations: ^1.1.1

  # --- Câmera e Imagem ---
  camera: ^0.11.0+2
  path_provider: ^2.1.5
  path: ^1.9.0
  flutter_image_compress: ^2.3.0

  # --- API e Rede ---
  dio: ^5.4.3+1
  http: ^1.2.0
  flutter_dotenv: ^5.1.0

  # --- Utilidades ---
  url_launcher: ^6.2.6
  intl: ^0.20.2
  shared_preferences: ^2.2.0

  google_maps_apis: ^1.0.5
  flutter_google_places_sdk: ^0.3.0
  cupertino_icons: ^1.0.8
  fl_chart: ^1.1.1
  pdf: ^3.11.3
  printing: ^5.14.2
  share_plus: ^12.0.1
  open_filex: ^4.5.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  uuid: ^4.5.1
  image_picker: ^1.1.2
  file_picker: ^8.1.4
  geolocator: ^14.0.2
  table_calendar: ^3.2.0
  record: ^6.1.2 # Added for Sound Analysis
  speech_to_text: ^7.3.0
  permission_handler: ^12.0.1
  google_mlkit_text_recognition: ^0.13.0
  purchases_flutter: ^9.10.2
  auto_size_text: ^3.0.0

  # --- Segurança e Backup ---
  cryptography: ^2.9.0
  archive: ^4.0.7
  crypto: ^3.0.3
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  # --- Ativos do App ---
  assets:
    - .env
    - assets/animations/
    - assets/images/
    - assets/data/
    - imagens/
